### ISSUE TITLE
Unable to access Dataset, waiting for approval

### ISSUE THREAD

**Issue by GiuseppeCartella** [CSAILVision/ADE20K#10]
Hi,
I will start in few days my Computer Vision project at university. The purpose is to segment indoor rooms. I would like to use the ADE20K dataset for training my model. my login is: igghi2, I did the request few weeks ago.
Is it possible to accept my request to the dataset ?
Thanks.

**Comment by henriksod** [comment]
Hi, I am also waiting for my approval.  // henriksod

**Comment by babyjia** [comment]
metoo,babyjia

**Comment by xavierpuigf** [comment]
Thanks for the note! I approved the accounts
