### ISSUE TITLE
Unable to load image using ade20k_starter.ipynb

### ISSUE THREAD

**Issue by vickyskarthik** [CSAILVision/ADE20K#2]
Hi
When I try to Load a segmentation object as provided by the ade20k_starter.ipynb I receive the following error.  Is my dataset incomplete or am I missing something?

FileNotFoundError: [Errno 2] No such file or directory: 'D:\\deft and tact\\vickyskarthik88_6d602e54\\ADE20K_2021_17_01/ADE20K_2021_17_01/images/ADE/training/urban/street/ADE_train_00016869_seg.png'

Thanks

**Comment by xavierpuigf** [comment]
It seems like you included the name of the folder in your path, you should only include the path where the dataset is stored:

`tact\vickyskarthik88_6d602e54\`

**Comment by vickyskarthik** [comment]
Thanks
