### ISSUE TITLE
Thing and stuff categories

### ISSUE THREAD

**Issue by nmddc0211** [CSAILVision/ADE20K#27]
Hi thanks for the wonderful dataset,
I am wondering, is there any way to determine whether a category is a "thing" (countable) or a "stuff" (uncountable) other than go through objectPresence? Even if I did this, some countable objects are still categorized as "uncountable" because they just appear once in the whole dataset (like abacus, airport cart,...)

Thanks
Dang

**Comment by xavierpuigf** [comment]
Hi! We did the object/stuff annotation for the 150 categories of the ADE20K challenge. You can find the stuff/thing labels in this file. https://github.com/CSAILVision/ADE20K/blob/main/utils/ade20k_instance_catid_mapping.txt

To map from the category indices to the ADE20K 150 categories, you can use this file: https://github.com/CSAILVision/ADE20K/blob/main/utils/ade20k_instance_catid_mapping.txt
