### ISSUE TITLE
I can't register dataset

### ISSUE THREAD

**Issue by ngodinhvu123** [CSAILVision/ADE20K#42]
when I click Register full dataset, the website navigates an empty page!
![image](https://github.com/CSAILVision/ADE20K/assets/48504459/c764fb85-e6f4-4c4e-aa74-e991ee2382d2)

**Comment by ngodinhvu123** [comment]
this is my mistake, I closed issue

**Comment by LISUJUN181171** [comment]
ngodinhvu123, Hello! May I ask if you could share the ADE20k dataset? The current dataset is no longer available for download. Thank you very much. My email address: 1811710128@qq.com

**Comment by ngodinhvu123** [comment]
You can download in the huggingface

https://huggingface.co/datasets?sort=downloads&search=Ade20k
