### ISSUE TITLE
Problem with registering my email.

### ISSUE THREAD

**Issue by deanAirre** [CSAILVision/ADE20K#45]
Hello ADE20k maintainers, I hope you guys have a great day.

I have been trying to register in order to use your dataset and have been waiting for the verification email for 4 hours or more. Is there any problem with my registration data as dean05? Thanks in advance!

Dean_05

**Comment by AniTho** [comment]
Were you able to download dataset?

**Comment by deanAirre** [comment]
Not yet

**Comment by xavierpuigf** [comment]
Should be solved now. Thanks to @kswain55 for solving this!
