### ISSUE TITLE
Could not receive activation link when registering

### ISSUE THREAD

**Issue by toffeecat** [CSAILVision/ADE20K#46]
Hi, i have met some problems when registering. After trying for several times, I still could not receive activation link from my email. My username is zilezile, can you help me with that.

**Comment by Isuru-Pradeep** [comment]
I also have the same problem

**Comment by VVogelimkafig** [comment]
same question
sad😭

**Comment by zkf85** [comment]
Same problem here!! So annoying!

**Comment by sajjad-sh33** [comment]
same problem

**Comment by xavierpuigf** [comment]
Should be solved now. Thanks to @kswain55 for solving this!

**Comment by LISUJUN181171** [comment]
Xavier Puigf, Hello! May I ask if you could share the ADE20k dataset? The current dataset is no longer available for download. Thank you very much. My email address: 1811710128@qq.com
