### ISSUE TITLE
Registration Page broken

### ISSUE THREAD

**Issue by mbookhahn** [CSAILVision/ADE20K#47]
Hi and many thanks for providing this dataset.

Unfortunately the registration page is broken. Is there any chance, you can fix this?

Best Regards!

**Comment by vstegmaier** [comment]
I have the same issue

**Comment by jiugexuan** [comment]
I have the same issue

**Comment by renespeck** [comment]
I also would like to download the dataset but instead i end up in the PHP login code: https://groups.csail.mit.edu/vision/datasets/ADE20K/request_data/login.php

**Comment by Murnomous24** [comment]
i have same problem. sad

**Comment by LainyLian** [comment]
Same goes here. In the step of registration, after filling in all information required, the system said: Fatal error attempting mail, contact your server administrator. Tested several email addresses, but still no change.

**Comment by joonielee832** [comment]
Same here

**Comment by Tim900216** [comment]
I have the same problem

**Comment by xavierpuigf** [comment]
Should be solved now. Thanks to @kswain55 for solving this!

**Comment by LISUJUN181171** [comment]
xavierpuigf 您好，请问您可以分享一下ADE20k数据集吗？现在这个数据集无法下载了，非常感谢您。我的邮箱：1811710128@qq.com
