### ISSUE TITLE
Can't download ADE20K after registration.

### ISSUE THREAD

**Issue by LWShowTime** [CSAILVision/ADE20K#48]
![image](https://github.com/user-attachments/assets/816b8526-0597-4fab-bc52-5fea7dc321f5)
From three months, can't download ADE20K using the url. Issue is recorded as the screen shot shows.

**Comment by futurev** [comment]
same here. is anyone looking into it?

**Comment by futurev** [comment]
@xavierpuigf

**Comment by xavierpuigf** [comment]
I believe we solved it this weekend. Could you refresh your browser/delete cache and login again?
I just tried downloading and succeeded

**Comment by LWShowTime** [comment]
Thanks @xavierpuigf Everything works well now!

**Comment by LISUJUN181171** [comment]
LWShowTime Hello, may I ask if you could share the ADE20k dataset? The current dataset is no longer available for download. Thank you very much. My email address: 1811710128@qq.com
