### ISSUE TITLE
Access to dataset

### ISSUE THREAD

**Issue by DaraOrange** [CSAILVision/ADE20K#5]
Hello! I try to get an access for your dataset from site, but I still see such message when log in:

_Your access to the dataset is pending approval. When you are approved, a link will appear in this page_

Can you please accept my request? My login is DaraOrange, I'm a student of Computer Science from NRU HSE and I need this dataset for my research in CV very much.

**Comment by xavierpuigf** [comment]
Thanks for the note! You should have access now.
